### ISSUE TITLE
The audio device is unaccessible

### ISSUE THREAD

**Issue by fgsch** [fgsch/docker-webex#5]
After recent changes audio is not working.

Ref #4.

**Comment by tevaum** [comment]
Any ideas about how to solve this? Is there any info I should add to help figuring out what the problem is?

**Comment by fgsch** [comment]
I will try to take a look at this week. I hope whatever bug I was experiencing with virtualbox is fixed in the new release.

**Comment by N0rbert** [comment]
Still a problem. Steps to reproduce:
1. Log in to webex.com conference via docker'd Firefox 52 as presenter,
1. it downloaded `CiscoWebExServlet`, 
1. then it launched Cisco Webex Training 
1. In opened Audio Conference window switched to *Use Computer for Audio*
1. Clicked *Call Using Computer*
1. Got error/warning message *The Audio device is unaccesible now.*

So audio does not work out the box.

**Comment by N0rbert** [comment]
Still a problem. Steps to reproduce:
1. Log in to webex.com conference via docker'd Firefox 52 as presenter,
1. it downloaded `CiscoWebExServlet`, 
1. then it launched Cisco Webex Training 
1. In opened Audio Conference window switched to *Use Computer for Audio*
1. Clicked *Call Using Computer*
1. Got error/warning message *The Audio device is unaccesible now.*

So audio does not work out the box.

**Comment by N0rbert** [comment]
Still a problem. Steps to reproduce:
1. Log in to webex.com conference via docker'd Firefox 52 as presenter,
1. it downloaded `CiscoWebExServlet`, 
1. then it launched Cisco Webex Training 
1. In opened Audio Conference window switched to *Use Computer for Audio*
1. Clicked *Call Using Computer*
1. Got error/warning message *The Audio device is unaccesible now.*

So audio does not work out the box.

**Comment by N0rbert** [comment]
Still a problem. Steps to reproduce:
1. Log in to webex.com conference via docker'd Firefox 52 as presenter,
1. it downloaded `CiscoWebExServlet`, 
1. then it launched Cisco Webex Training 
1. In opened Audio Conference window switched to *Use Computer for Audio*
1. Clicked *Call Using Computer*
1. Got error/warning message *The Audio device is unaccesible now.*

So audio does not work out the box.

**Comment by N0rbert** [comment]
Still a problem. Steps to reproduce:
1. Log in to webex.com conference via docker'd Firefox 52 as presenter,
1. it downloaded `CiscoWebExServlet`, 
1. then it launched Cisco Webex Training 
1. In opened Audio Conference window switched to *Use Computer for Audio*
1. Clicked *Call Using Computer*
1. Got error/warning message *The Audio device is unaccesible now.*

So audio does not work out the box.

**Comment by N0rbert** [comment]
Still a problem. Steps to reproduce:
1. Log in to webex.com conference via docker'd Firefox 52 as presenter,
1. it downloaded `CiscoWebExServlet`, 
1. then it launched Cisco Webex Training 
1. In opened Audio Conference window switched to *Use Computer for Audio*
1. Clicked *Call Using Computer*
1. Got error/warning message *The Audio device is unaccesible now.*

So audio does not work out the box.

**Comment by N0rbert** [comment]
Still a problem. Steps to reproduce:
1. Log in to webex.com conference via docker'd Firefox 52 as presenter,
1. it downloaded `CiscoWebExServlet`, 
1. then it launched Cisco Webex Training 
1. In opened Audio Conference window switched to *Use Computer for Audio*
1. Clicked *Call Using Computer*
1. Got error/warning message *The Audio device is unaccesible now.*

So audio does not work out the box.

**Comment by N0rbert** [comment]
This happens for client version 40.8.7.13 .
